"""init_tables

Revision ID: 08267a6b144c
Revises: 
Create Date: 2026-01-11 18:48:55.984519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08267a6b144c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sk_user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sk_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sk_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sk_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sk_user_email'))

    op.drop_table('sk_user')
    # ### end Alembic commands ###
